openapi: "3.0.3"
info:
  title: Contact API
  description: Contact API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/contact:
    get:
      description: Search for contact
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - name: name
          in: query
          description: name of the contact
          example: John Doe
        - name: email
          in: query
          description: email of the contact
          example: example@gmail.com
        - name: phone
          in: query
          description: phone of the contact
          example: 123456789
        - name: size
          in: query
          description: number of contacts to return
          example: 1
        - name: page
          in: query
          description: page number
          example: 1
      responses:
        '200':
          description: Success search contacts
          content:
            application/json:
              examples:
                one found:
                  value:
                    contacts:
                      - id: 1
                        first name: John
                        last name: Doe
                        email: example@gmail.com
                        phone: 123456789
                    meta: {
                      size: 1,
                      page: 1
                    }
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/ContactModel'
                  meta:
                    type: object
        default:
            $ref: '#/components/responses/DefaultError'
    post:
      description: Create a new contact
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        content:
          application/json:
            examples:
              contact inserted:
                $ref: '#/components/examples/ContactChange'
            schema:
              $ref: '#/components/schemas/ContactMain'
      responses:
        '201':
          description: Success successfully created
          content:
            application/json:
              examples:
                contact created:
                  $ref: '#/components/examples/ContactModelValue'
              schema:
                $ref: '#/components/schemas/ContactModel'
        default:
          $ref: '#/components/responses/DefaultError'
  /api/contact/{id}:
    get:
      description: Get contact by id
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ContactPath'
      responses:
        '200':
          description: Contact successfully found
          content:
            application/json:
              examples:
                contact:
                  $ref: '#/components/examples/ContactModelValue'
              schema:
                $ref: '#/components/schemas/ContactModel'
        default:
          $ref: '#/components/responses/DefaultError'
    put:
      description: Update contact by id
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ContactPath'
      requestBody:
        content:
          application/json:
            examples:
              contact updated:
                $ref: '#/components/examples/ContactChange'
            schema:
              $ref: '#/components/schemas/ContactMain'
      responses:
        '200':
          description: Contact successfully updated
          content:
            application/json:
              examples:
                updated contact:
                  $ref: '#/components/examples/ContactModelValue'
              schema:
                $ref: '#/components/schemas/ContactModel'
        default:
          $ref: '#/components/responses/DefaultError'
    delete:
      description: Delete contact by id
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ContactPath'
      responses:
        '200':
          description: Contact successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        default:
          $ref: '#/components/responses/DefaultError'
components:
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      description: Authorization token
      example: dXNlcjpwYXNzd29yZA==
    ContactPath:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
      example: 1
  schemas:
    ContactMain:
      type: object
      properties:
        first name:
          type: string
        last name:
          type: string
        email:
          type: string
        phone:
          type: string
    ContactId:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
    ContactModel:
      type: object
      properties:
        contact:
          allOf:
            - $ref: '#/components/schemas/ContactId'
            - $ref: '#/components/schemas/ContactMain'
  examples:
    ContactModelValue:
      value:
        contact:
          id: 1
          first name: John
          last name: Doe
          email: example@gmail.com
          phone: 123456789
    ContactChange:
      value:
        first name: John
        last name: Doe
        email: example@gmail.com
        phone: 123456789
  responses:
    DefaultError:
      description: Unexpected error
      content:
        application/json:
          examples:
            error:
              value:
                message: Unexpected error
                data: {data: 'this is an example'}
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                  data:
                    type: object
                    description: Additional error data
